# This is a basic workflow to help you get started with Actions
# CI 라는 워크 플로우이며 
name: Hello Team

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # 깃헙 액션이 체크아웃이 필요하다.
      - uses: actions/checkout@v2

      - name: Hello Team
        uses: ./.github/actions/hello-team
        with:
          member: "Hyung Joo"
          leader: "Justin"
