name: Random Joke

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Random Joke Action for team
        uses: ./.github/actions/random-joke